#!/bin/bash
#change the path if you installed it on an other location
cd ~/.local/share/orca/plugins/plugins-available

if [ -e "../plugins-enabled/$1" ]; then
    unlink "../plugins-enabled/$1"
else
    echo "$1 is not enabled."
fi
