#!/bin/bash
installpath=/usr/share/SOPS
pluginpath=$HOME/.local/share/orca/plugins/plugins-enabled
filename=$(basename "$1")
if [ -e "$pluginpath/$filename" ]; then
    echo "$1 is already enabled."
    exit 1
else
    mkdir -p $pluginpath/
    ln -s "$installpath/plugins/plugins-available/$1" $pluginpath/
fi
exit 0

