#!/bin/bash
pluginpath=$HOME/.local/share/orca/plugins/plugins-enabled
filename=$(basename "$1")
if [ -e "$pluginpath/$filename" ]; then
    echo "$1 is already enabled."
    exit 1
else
    if [[ -x "$1" ]]; then
        chmod +x "$1"
    fi
    mkdir -p $pluginpath/
    ln -s "$1" $pluginpath/
fi
exit 0
