#!/bin/bash
pluginpath="${XDG_CONFIG_HOME:-$HOME/.config}/SOPS/plugins-enabled"
if [ -e "$pluginpath/${1##*/}" ]; then
    unlink "$pluginpath/${1##*/}"
else
    echo "${1##*/} is not enabled."
    exit 1
fi
exit 0
