#!/bin/bash

installpath=/usr/share/SOPS
pluginpath=$HOME/.config/SOPS/plugins-enabled
filename=$(basename "$1")
# Error checking, make sure the plugin actually exists
if ! [ -f "$1" ]; then
    echo "Plugin $filename not found."
    exit 1
fi

if [ -e "$pluginpath/$filename" ]; then
    echo "$1 is already enabled."
    exit 1
else
    mkdir -p $pluginpath/
    ln -s "$installpath/plugins/plugins-available/$1" $pluginpath/
fi
exit 0

